### PR TITLE
Add bottom navigation bar & create temporary screens for donate, news, and more

### PR DESCRIPTION
**Pull request by aahmad4**
* Added bottom navigation bar & create temporary screens for donate, news, and more
* Reformated some files as well

### CODE REVIEW

**Comment by z3bi** [comment]
@aahmad4  we can go ahead and make a "MoreScreen" as well. It's going to have a few things like settings in there.

**Comment by z3bi** [comment]
@aahmad4 I would recommend not doing the reformatting in the same PR as something else, makes its very hard to review what changed.

**Comment by z3bi** [comment]
Also in general it's nice to agree on a formatting style before reformatting the project :)

**Comment by aahmad4** [comment]
> @aahmad4 I would recommend not doing the reformatting in the same PR as something else, makes its very hard to review what changed.

Yeah, I apologize for that 😓

**Comment by aahmad4** [comment]
> Also in general it's nice to agree on a formatting style before reformatting the project :)

Yeah definitely, I think this was just using the default formatting style with "Cntrl + Alt+ L"

**Review by z3bi — APPROVED** [review]

**Pull request merged**
